### ISSUE TITLE
请问有没有关于搜狗bin词库格式的文档？

### ISSUE THREAD

**Issue by studyzy** [h4x3rotab/Sogou-User-Dict-Converter#1]
您好，我是深蓝词库转换的作者，您这个bin词库解析太厉害了！佩服！
我想将您的搜狗bin词库解析算法用C#重写到我这个软件中，但是我Python不熟悉，看源码还比较痛苦，请问您那边有解析bin词库格式的文档吗？

**Comment by studyzy** [comment]
已经有人用C#重写了，新版本已发布。谢谢！

**Comment by h4x3rotab** [comment]
那太好了，求地址

**Comment by studyzy** [comment]
https://github.com/studyzy/imewlconverter/blob/master/IME%20WL%20Converter/IME%20WL%20Converter/IME/SougouPinyinBinFromPython.cs

**Comment by studyzy** [comment]
@h4x3rotab 这么复杂的结构，你是怎么分析出来的？实在佩服。
